neighborhood/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Myneighbor.urls')),
    path('users/', include('users.urls')),
    path('business/', include('business.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.loginUser, name='login'),
    path('logout/', views.logoutUser, name='logout'),
    path('register/', views.registerUser, name='register'),

    path('', views.profiles, name='profiles'),
    path('profile/<str:pk>', views.userProfile, name='user-profile'),
]

Myneighbor/models.py
import uuid
from django.db import models
from users.models import Profile

# Create your models here.
class Neighbor(models.Model):
    user= models.ForeignKey(Profile,null=True,blank=True,on_delete=models.SET_NULL)
    name=models.CharField(max_length=200)
    location=models.CharField(max_length=200,null=True,blank=True)
    occupation=models.CharField(max_length=200,null=True,blank=True)
    featured_image = models.ImageField(null=True,blank=True, default="default.jpg")
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4,unique=True,primary_key=True,editable=False)


    def __str__(self):
        return self.name






class Post(models.Model):
    title=models.CharField(max_length=200)
    post = models.TextField()
    neighbor = models.ForeignKey(Neighbor, on_delete=models.CASCADE, blank=True) 
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4,unique=True,primary_key=True,editable=False) 



    def __str__(self):
        return self.title

users/models.py
# from distutils.command.upload import upload
# import email
# from email.policy import default
# from unicodedata import name
import email
import uuid
from django.db import models
from django.contrib.auth.models import User

# from django.db.models.signals import post_save,post_delete
# from django.dispatch import receiver

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE,null=True,blank=True)
    name=models.CharField(max_length=200,blank=True,null=True)
    email=models.EmailField(max_length=500,null=True,blank=True)
    profile_image=models.ImageField(null=True,blank=True,upload_to='profiles/', default="default.jpg")
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4,unique=True,primary_key=True,editable=False) 

    def __str__(self):
        return str(self.name)

# @receiver(post_save, sender=Profile)
# def createProfile(sender,instance,created,**kwargs):
#     if created:
#         user=instance
#         profile=Profile.objects.create(
#             user=user,
#             email=user.email,
#             name=user.username,
          
#         )


# def deleteUser(sender,instance,**kwargs):
#     user=instance.user
#     user.delete()
    

# post_save.connect(createProfile, sender=User)   
# post_delete.connect(deleteUser,sender=Profile)     

users/forms.py
from cProfile import label
from django.forms  import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class CustomUserCreation(UserCreationForm):
    class Meta:
        model=User
        fields=['username','email','password1','password2']
        labels={
            
        }


    def __init__(self, *args,**kwargs):
        super(CustomUserCreation,self).__init__(*args,**kwargs)

        for name,field in self.fields.items():
            field.widget.attrs.update({'class':'un'})     

users/views.py
# from multiprocessing import context
from django.shortcuts import render,redirect
from django.contrib.auth import login,authenticate,logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
# from django.contrib.auth.forms import UserCreationForm
from .forms import CustomUserCreation
from django.contrib.auth.models import User
from .models import Profile

# Create your views here.
def loginUser(request):
    page='login'

    if request.user.is_authenticated:
        return redirect('neighbors')
    
    if request.method=='POST':
        username=request.POST['username']
        password=request.POST['password']
        try:
            user=User.objects.get(username=username)

        except:
            messages.error(request,'Username does not exist')    

        user=authenticate(request,username=username, password=password)   

        if user is not None:
            login(request,user)
            return redirect('neighbors') 
        else:
              messages.error(request,"user name or password is incorrect")    

    return render(request, 'users/login_register.html')


def logoutUser(request):
    logout(request)
    messages.info(request, "User wa successfullt logout")    
    return redirect('login')


def registerUser(request):
    page='register'
    form=CustomUserCreation()

    if request.method =='POST':
        form =CustomUserCreation(request.POST)
        if form.is_valid():
            user=form.save(commit=False)
            user.username=user.username.lower()
            user.save()

            messages.success(request,'User account wa created')

            login(request,user)
            return redirect('neighbors')

        else:
             messages.error(request,'registration not successfully')


    context={'page':page,'form':form}
    return render(request, 'users/login_register.html',context)

def profiles(request):
    profiles=Profile.objects.all()
    context={ 'profiles':profiles}
    return render(request, 'users/profiles.html',context)

def userProfile(request,pk):
    profile=Profile.objects.get(id=pk)
    context={'profile':profile}
    return render(request, 'users/user-profile.html',context)    

users/templates/users/login_register.html
{% extends 'base.html' %}

{% block content %}

{% if page == 'register' %}
<!-- <h1>Register</h1>
<form method="POST" action="{% url 'register' %}">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="register User"/>
</form>
<p>Already have an account<a href="{% url 'login' %}">Sign In</a></p> -->



<div class="main">
    <p class="sign" align="center">Sign Up</p>
    <form class="form1" method="POST" action="{% url 'register' %}">
        {% csrf_token %}
        {% for field in form %}
        <label for='label'>{{field.label}}</label>
      {{field}}
       
      {% for error in field.errors %}
      <p style="color:red">{{error}}</p>
      {% endfor %}

      {% endfor %}
      <input type="submit" class="submit" align="center" value="register User"/>
      <!-- <a class="submit" align="center">Login</a> -->
      <p class="forgot" align="center">You already  have an Account, <a href="{% url 'login' %}">login</a></p>
            
                
    </div>

    {% else %}
<!-- 
<form action="{% url 'login' %}" method="POST">
    {% csrf_token %}
    <input type="text" name="username"/>
    <input type="password" name="password"/>
    <input type="submit" name="Login"/>

    <p>Dont't have an account<a href="{% url 'register' %}">Sign Up</a></p>
</form>  -->


<div class="main">
    <p class="sign" align="center">Sign in</p>

    <form class="form1" action="{% url 'login' %}" method="POST">
        {% csrf_token %}
      <input class="un " type="text" align="center" name="username" placeholder="Username">
      <input class="pass" type="password" align="center" name="password" placeholder="Password">
      <input type="submit" class="submit" align="center" name="Login"/>
      <p class="forgot" align="center">You dont have an Account, <a href="{% url 'register' %}">register</a></p>
            
                
    </div>

{% endif %}
{% endblock %}

users/templates/users/profiles.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        {% for profile in profiles %}
        <div class="col-md-5 mt-5">
            <a href="{% url 'user-profile' profile.id %}">
            <div class="card" style="width: 18rem;">
                <img src="{{ profile.profile_image.url}}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h4><b>{{profile.name}}</b></h4> 
                      <p>{{profile.email}}</p> 
                </div>
              </div>
            </a>
        </div>
        {% endfor %}
        </div>
        </div>
        

{% endblock %}

users/templates/users/user-profile.html
{% extends 'base.html' %}

{% block content %}
<main class="profile mt-6">
    <div class="container">
      <div class="row">
        <div class="col-md-4">
          <div class="">
            <div class="mx-6">
              <img class="img-fluid" style="width: 100px; height: 100px; border-radius: 50%; margin-top: 20px;" src="{{ profile.profile_image.url}}" />
              <h2 class="dev__name">{{profile.name}}</h2>
              <p class="dev__title">{{profile.email}}</p>
              
             
            </div>
          </div>
        </div>
       
          <div class="col-md-8 mt-20">
            <h3>Neighbours</h3>
            <div class="">
             {% for neighbor in profile.neighbor_set.all %}
              <div class="column mt-20">
                <div class="card" style="width: 360px; margin: 20px;">
                  <a href="{% url 'neighbor' neighbor.id %}" class="neighbour">
                    <img class="project__thumbnail" style="width:fit-content; height: 200px;" src="{{neighbor.featured_image.url }}" alt= "thumbnail" />
                    <div class="card__body">
                        <h5 class="card-title">{{neighbor.name}}</h5>
                        <p>Neighbour to <strong>{{neighbor.user.name}}</strong></p>
                        <p class="card-text">{{neighbor.location}}</p>
                        <p class="card-text"><strong>{{neighbor.occupation}}</strong></p>
                       <p><a class="btn btn-dark" href="{% url 'update-neighbor' neighbor.id %}">Edit</a></p>
                       <p><a class="btn btn-dark" href="{% url 'delete-neighbor' neighbor.id %}">Delete</a></p>
                  </a> 
                </div>
              </div>
              {% endfor %}

            
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>
{% endblock %}